version: 3.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

install:
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore

assembly_info:
  patch: true
  file: SolutionInfo.*
  assembly_version: "3.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

cache:
  - packages -> paket.lock

nuget:
  account_feed: true
  project_feed: true

build:
  parallel: true
  project: fluentwindsor.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

after_test:
  - cmd: pack.bat
  
artifacts:
  - path: /.*\.(dll|pdb|nupkg)/

deploy:
  
  provider: GitHub
  release: fluentwindsor-v$(appveyor_build_version)
  description: 'For making Windsor super easy'
  auth_token:
    secure: sZD4+HypTqlQYLcBv+EkKIc0EWYGkeT4LUXmY0ALqyDQH6n++fBAQZTHaltI4SsM 
  artifact: /.*\.(dll|pdb|nupkg)/       
  draft: false
  prerelease: false
  on:
    branch: master                 
  appveyor_repo_tag: true

  provider: NuGet
  api_key:
    secure: GYMQ4rHqUYL5BcjMn2L9cs72K4YwEPfGRK9VWj1w6PswqbEWKrGUKICa064OUKRD
  skip_symbols: false
  artifact: /.*\.nupkg/